CREATE TABLE "evaluation_stations" ("id" TEXT NOT NULL PRIMARY KEY,"name" TEXT NOT NULL,"type" TEXT NOT NULL,"order" INTEGER NOT NULL DEFAULT 0,"eventId" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "evaluation_stations_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "phases" ("id" TEXT NOT NULL PRIMARY KEY,"name" TEXT NOT NULL,"type" TEXT NOT NULL,"sequence" INTEGER NOT NULL,"durationSeconds" INTEGER NOT NULL,"calibrationSeconds" INTEGER NOT NULL DEFAULT 0,"eventId" TEXT NOT NULL,CONSTRAINT "phases_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "phases_eventId_sequence_key" ON "phases"("eventId","sequence");
CREATE TABLE "schedule_slots" ("id" TEXT NOT NULL PRIMARY KEY,"eventId" TEXT NOT NULL,"phaseId" TEXT NOT NULL,"stationId" TEXT NOT NULL,"teamId" TEXT NOT NULL,"scheduledAt" DATETIME NOT NULL,"order" INTEGER NOT NULL,"status" TEXT NOT NULL DEFAULT 'SCHEDULED',CONSTRAINT "schedule_slots_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "schedule_slots_phaseId_fkey" FOREIGN KEY ("phaseId") REFERENCES "phases" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "schedule_slots_stationId_fkey" FOREIGN KEY ("stationId") REFERENCES "evaluation_stations" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "schedule_slots_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "teams" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX "schedule_slots_stationId_scheduledAt_idx" ON "schedule_slots"("stationId","scheduledAt"); CREATE INDEX "schedule_slots_teamId_phaseId_idx" ON "schedule_slots"("teamId","phaseId");
CREATE TABLE "terminals" ("id" TEXT NOT NULL PRIMARY KEY,"deviceKey" TEXT NOT NULL,"name" TEXT NOT NULL,"eventId" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "terminals_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events" ("id") ON DELETE CASCADE ON UPDATE CASCADE); CREATE UNIQUE INDEX "terminals_deviceKey_key" ON "terminals"("deviceKey");
CREATE TABLE "evaluation_sessions" ("id" TEXT NOT NULL PRIMARY KEY,"slotId" TEXT NOT NULL,"state" TEXT NOT NULL DEFAULT 'SCHEDULED',"calibrationStartedAt" DATETIME,"startedAt" DATETIME,"finishedAt" DATETIME,"scorecard" TEXT NOT NULL DEFAULT '{}',"version" INTEGER NOT NULL DEFAULT 1,"operatorName" TEXT,"terminalId" TEXT,CONSTRAINT "evaluation_sessions_slotId_fkey" FOREIGN KEY ("slotId") REFERENCES "schedule_slots" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "evaluation_sessions_terminalId_fkey" FOREIGN KEY ("terminalId") REFERENCES "terminals" ("id") ON DELETE SET NULL ON UPDATE CASCADE); CREATE UNIQUE INDEX "evaluation_sessions_slotId_key" ON "evaluation_sessions"("slotId");
CREATE TABLE "terminal_usages" ("id" TEXT NOT NULL PRIMARY KEY,"terminalId" TEXT NOT NULL,"stationId" TEXT NOT NULL,"operatorName" TEXT,"startedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"endedAt" DATETIME,CONSTRAINT "terminal_usages_terminalId_fkey" FOREIGN KEY ("terminalId") REFERENCES "terminals" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "audit_logs" ("id" TEXT NOT NULL PRIMARY KEY,"eventId" TEXT NOT NULL,"action" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT NOT NULL,"stationId" TEXT,"teamId" TEXT,"terminalId" TEXT,"operatorName" TEXT,"actorRole" TEXT,"before" TEXT,"after" TEXT,"reason" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "audit_logs_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events" ("id") ON DELETE CASCADE ON UPDATE CASCADE); CREATE INDEX "audit_logs_eventId_createdAt_idx" ON "audit_logs"("eventId","createdAt"); CREATE INDEX "audit_logs_stationId_createdAt_idx" ON "audit_logs"("stationId","createdAt");
